coursework
dariiadovha/Python-Basic-Course pull request #7
Opened 2018-04-19 14:48 UTC by dariiadovha

for me looks fine, dict is generated
however, the csv files are not created
please advise as i do not understand the debugger output

2018-04-23 17:52 UTC, voronov007 requested changes
Впринцыпе неплохо, но можно сделать лучше. Исправить проверку телефона и карточки. Используйте выши предыдущие решения. Я так понимаю, что вам защитать сразу эту курсовую и как домашку с записью файла?

2018-04-23 17:52 UTC, voronov007 commented on final_project/utils/__init__.py
> +            phone_number = '+'
`phone_number = '+'` already exists

2018-04-23 17:52 UTC, voronov007 commented on final_project/utils/__init__.py
> +            card_number+=str(random.choice(symbols))
random symbol only at the end. Not the best decision, just simple one.

2018-04-23 17:52 UTC, voronov007 commented on final_project/utils/__init__.py
> +            matched_phone = pattern.match(compiled_dict.get('Phone'))
у вас есть готовые функции для проверки телефона и карточки их можно и нужно было использовать. 
re.compile(' ''-' '[a-zA-Z]') не опишет полностью проверку телефона. Вы пробовали запустить код? В этой части будут ошибки.

2018-04-23 17:52 UTC, voronov007 commented on final_project/utils/__init__.py
> +    return ()
а что возвращает функция? Если ничего не возвращает, то return не нужен. Можно просто использовать return если нужно выйти из функции раньше времени.

2018-04-23 17:53 UTC, voronov007 reviewed
Функции нужно было писать не в `__init__` а в соседний модуль, а потом импортить в init

2018-04-23 17:55 UTC, voronov007 commented
Нету ДЗ 6

2018-04-23 21:34 UTC, dariiadovha commented on final_project/utils/__init__.py
> +            matched_phone = pattern.match(compiled_dict.get('Phone'))
да, но как потом эти все функции интегрировать в функцию? Или это должна быть замкнутая функция? Или я должна включить все функции сюда, а вынести импорт в файл в основную часть кода, где я буду поочередно их вызывать? я хотела все записать в одной

2018-04-24 08:26 UTC, voronov007 commented on final_project/utils/__init__.py
> +            matched_phone = pattern.match(compiled_dict.get('Phone'))
у тебя есть, например, модуль `my_useful_functions`, который лежит в той же директории, что и `__init__`. в my_useful_functions пишешь свои функции, а потом ипортируешь их в `__init__`. После этого ты можешь импортировать функции из пакета `from utils import <function1>, ...`.
Зачем нужно импортировать в `__init__`? Во превый, что бы можно было запистаь так `from utils import <function1>, ...`. Во вторых, у тебя в пакете может быть другой модуль, например, `my_useful_generators.py` и в нем будут функции для генерирования данных. То етсь ты разделяешь модули по смыслу и тем легче будет читать твою программу. Именно поэтмоу никто не пишет `__init__.py`. Потому что можно и нужно создавать несколько модулей, который будут содержать нужные функции или классы или что-то еще. Разделяй и властвуй.

2018-04-24 08:30 UTC, voronov007 reviewed
Исправить

2018-04-24 08:30 UTC, voronov007 commented on final_project/utils/__init__.py
> +            matched_card = pattern.match(compiled_dic.get('Card'))
Я не вижу у вас ДЗ6, мы писали проверку карточки:
https://github.com/SergeyKot987/python_basic_course/pull/6/files#diff-0c7f447c99d43439157e362aedfbe5f7R8

2018-04-24 21:51 UTC, closed without merging